name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://registry.npmjs.org'
      - name: NPM install
        run: npm ci
      - name: Build web components
        run: |
          npm run test:wc
          npm run build:wc
      - name: Build host web
        run: |
          npm run test:web
          npm run build:web
      - name: Build host mobile
        run: |
          npm run test:mobile
          npm run build:mobile
